-- Carga da silver a partir da bronze, para uma competencia.
-- A janela por n_aih protege contra duplicidade dentro da propria carga.
-- O merge por n_aih resolve reapresentacao de AIH entre competencias, e a
-- condicao de competencia no WHEN MATCHED garante que carregar uma competencia
-- antiga depois de uma recente nao sobrescreva a versao mais nova.

MERGE INTO iceberg.silver.sih_aih AS destino
USING (
    SELECT
            uf_zi AS uf_zi,
            ano_cmpt AS ano_cmpt,
            mes_cmpt AS mes_cmpt,
            espec AS espec,
            cgc_hosp AS cgc_hosp,
            n_aih AS n_aih,
            ident AS ident,
            cep AS cep,
            munic_res AS munic_res,
            if(nasc = '18991230', NULL, try(cast(date_parse(nasc, '%Y%m%d') AS date))) AS nasc,
            sexo AS sexo,
            try_cast(uti_mes_in AS integer) AS uti_mes_in,
            try_cast(uti_mes_an AS integer) AS uti_mes_an,
            try_cast(uti_mes_al AS integer) AS uti_mes_al,
            try_cast(uti_mes_to AS integer) AS uti_mes_to,
            marca_uti AS marca_uti,
            try_cast(uti_int_in AS integer) AS uti_int_in,
            try_cast(uti_int_an AS integer) AS uti_int_an,
            try_cast(uti_int_al AS integer) AS uti_int_al,
            try_cast(uti_int_to AS integer) AS uti_int_to,
            try_cast(diar_acom AS integer) AS diar_acom,
            try_cast(qt_diarias AS integer) AS qt_diarias,
            proc_solic AS proc_solic,
            proc_rea AS proc_rea,
            try_cast(val_sh AS decimal(12,2)) AS val_sh,
            try_cast(val_sp AS decimal(12,2)) AS val_sp,
            try_cast(val_sadt AS decimal(12,2)) AS val_sadt,
            try_cast(val_rn AS decimal(12,2)) AS val_rn,
            try_cast(val_acomp AS decimal(12,2)) AS val_acomp,
            try_cast(val_ortp AS decimal(12,2)) AS val_ortp,
            try_cast(val_sangue AS decimal(12,2)) AS val_sangue,
            try_cast(val_sadtsr AS decimal(12,2)) AS val_sadtsr,
            try_cast(val_transp AS decimal(12,2)) AS val_transp,
            try_cast(val_obsang AS decimal(12,2)) AS val_obsang,
            try_cast(val_ped1ac AS decimal(12,2)) AS val_ped1ac,
            try_cast(val_tot AS decimal(12,2)) AS val_tot,
            try_cast(val_uti AS decimal(12,2)) AS val_uti,
            try_cast(us_tot AS decimal(12,2)) AS us_tot,
            try(cast(date_parse(dt_inter, '%Y%m%d') AS date)) AS dt_inter,
            try(cast(date_parse(dt_saida, '%Y%m%d') AS date)) AS dt_saida,
            diag_princ AS diag_princ,
            diag_secun AS diag_secun,
            cobranca AS cobranca,
            natureza AS natureza,
            nat_jur AS nat_jur,
            gestao AS gestao,
            rubrica AS rubrica,
            ind_vdrl AS ind_vdrl,
            munic_mov AS munic_mov,
            cod_idade AS cod_idade,
            try_cast(idade AS integer) AS idade,
            try_cast(dias_perm AS integer) AS dias_perm,
            if(morte IS NULL, NULL, morte = '1') AS morte,
            nacional AS nacional,
            num_proc AS num_proc,
            car_int AS car_int,
            try_cast(tot_pt_sp AS integer) AS tot_pt_sp,
            cpf_aut AS cpf_aut,
            homonimo AS homonimo,
            try_cast(num_filhos AS integer) AS num_filhos,
            instru AS instru,
            cid_notif AS cid_notif,
            contracep1 AS contracep1,
            contracep2 AS contracep2,
            gestrisco AS gestrisco,
            insc_pn AS insc_pn,
            seq_aih5 AS seq_aih5,
            cbor AS cbor,
            cnaer AS cnaer,
            vincprev AS vincprev,
            gestor_cod AS gestor_cod,
            gestor_tp AS gestor_tp,
            gestor_cpf AS gestor_cpf,
            gestor_dt AS gestor_dt,
            cnes AS cnes,
            cnpj_mant AS cnpj_mant,
            infehosp AS infehosp,
            cid_asso AS cid_asso,
            cid_morte AS cid_morte,
            complex AS complex,
            financ AS financ,
            faec_tp AS faec_tp,
            regct AS regct,
            raca_cor AS raca_cor,
            etnia AS etnia,
            try_cast(sequencia AS integer) AS sequencia,
            remessa AS remessa,
            aud_just AS aud_just,
            sis_just AS sis_just,
            try_cast(val_sh_fed AS decimal(12,2)) AS val_sh_fed,
            try_cast(val_sp_fed AS decimal(12,2)) AS val_sp_fed,
            try_cast(val_sh_ges AS decimal(12,2)) AS val_sh_ges,
            try_cast(val_sp_ges AS decimal(12,2)) AS val_sp_ges,
            try_cast(val_uci AS decimal(12,2)) AS val_uci,
            marca_uci AS marca_uci,
            diagsec1 AS diagsec1,
            diagsec2 AS diagsec2,
            diagsec3 AS diagsec3,
            diagsec4 AS diagsec4,
            diagsec5 AS diagsec5,
            diagsec6 AS diagsec6,
            diagsec7 AS diagsec7,
            diagsec8 AS diagsec8,
            diagsec9 AS diagsec9,
            tpdisec1 AS tpdisec1,
            tpdisec2 AS tpdisec2,
            tpdisec3 AS tpdisec3,
            tpdisec4 AS tpdisec4,
            tpdisec5 AS tpdisec5,
            tpdisec6 AS tpdisec6,
            tpdisec7 AS tpdisec7,
            tpdisec8 AS tpdisec8,
            tpdisec9 AS tpdisec9,
            substr(munic_res, 1, 2) AS uf_res,
            substr(munic_mov, 1, 2) AS uf_mov,
            "_competencia",
            "_source_file",
            "_ingested_at",
            cast(current_timestamp AS timestamp(6) WITH TIME ZONE) AS "_silver_at"
    FROM (
        SELECT *,
               row_number() OVER (
                   PARTITION BY n_aih
                   ORDER BY "_competencia" DESC, "_ingested_at" DESC
               ) AS versao
        FROM iceberg.bronze.sih_aih
        WHERE "_competencia" = ?
    )
    WHERE versao = 1
) AS origem
ON destino.n_aih = origem.n_aih
WHEN MATCHED AND origem."_competencia" >= destino."_competencia" THEN UPDATE SET
        uf_zi = origem.uf_zi,
        ano_cmpt = origem.ano_cmpt,
        mes_cmpt = origem.mes_cmpt,
        espec = origem.espec,
        cgc_hosp = origem.cgc_hosp,
        ident = origem.ident,
        cep = origem.cep,
        munic_res = origem.munic_res,
        nasc = origem.nasc,
        sexo = origem.sexo,
        uti_mes_in = origem.uti_mes_in,
        uti_mes_an = origem.uti_mes_an,
        uti_mes_al = origem.uti_mes_al,
        uti_mes_to = origem.uti_mes_to,
        marca_uti = origem.marca_uti,
        uti_int_in = origem.uti_int_in,
        uti_int_an = origem.uti_int_an,
        uti_int_al = origem.uti_int_al,
        uti_int_to = origem.uti_int_to,
        diar_acom = origem.diar_acom,
        qt_diarias = origem.qt_diarias,
        proc_solic = origem.proc_solic,
        proc_rea = origem.proc_rea,
        val_sh = origem.val_sh,
        val_sp = origem.val_sp,
        val_sadt = origem.val_sadt,
        val_rn = origem.val_rn,
        val_acomp = origem.val_acomp,
        val_ortp = origem.val_ortp,
        val_sangue = origem.val_sangue,
        val_sadtsr = origem.val_sadtsr,
        val_transp = origem.val_transp,
        val_obsang = origem.val_obsang,
        val_ped1ac = origem.val_ped1ac,
        val_tot = origem.val_tot,
        val_uti = origem.val_uti,
        us_tot = origem.us_tot,
        dt_inter = origem.dt_inter,
        dt_saida = origem.dt_saida,
        diag_princ = origem.diag_princ,
        diag_secun = origem.diag_secun,
        cobranca = origem.cobranca,
        natureza = origem.natureza,
        nat_jur = origem.nat_jur,
        gestao = origem.gestao,
        rubrica = origem.rubrica,
        ind_vdrl = origem.ind_vdrl,
        munic_mov = origem.munic_mov,
        cod_idade = origem.cod_idade,
        idade = origem.idade,
        dias_perm = origem.dias_perm,
        morte = origem.morte,
        nacional = origem.nacional,
        num_proc = origem.num_proc,
        car_int = origem.car_int,
        tot_pt_sp = origem.tot_pt_sp,
        cpf_aut = origem.cpf_aut,
        homonimo = origem.homonimo,
        num_filhos = origem.num_filhos,
        instru = origem.instru,
        cid_notif = origem.cid_notif,
        contracep1 = origem.contracep1,
        contracep2 = origem.contracep2,
        gestrisco = origem.gestrisco,
        insc_pn = origem.insc_pn,
        seq_aih5 = origem.seq_aih5,
        cbor = origem.cbor,
        cnaer = origem.cnaer,
        vincprev = origem.vincprev,
        gestor_cod = origem.gestor_cod,
        gestor_tp = origem.gestor_tp,
        gestor_cpf = origem.gestor_cpf,
        gestor_dt = origem.gestor_dt,
        cnes = origem.cnes,
        cnpj_mant = origem.cnpj_mant,
        infehosp = origem.infehosp,
        cid_asso = origem.cid_asso,
        cid_morte = origem.cid_morte,
        complex = origem.complex,
        financ = origem.financ,
        faec_tp = origem.faec_tp,
        regct = origem.regct,
        raca_cor = origem.raca_cor,
        etnia = origem.etnia,
        sequencia = origem.sequencia,
        remessa = origem.remessa,
        aud_just = origem.aud_just,
        sis_just = origem.sis_just,
        val_sh_fed = origem.val_sh_fed,
        val_sp_fed = origem.val_sp_fed,
        val_sh_ges = origem.val_sh_ges,
        val_sp_ges = origem.val_sp_ges,
        val_uci = origem.val_uci,
        marca_uci = origem.marca_uci,
        diagsec1 = origem.diagsec1,
        diagsec2 = origem.diagsec2,
        diagsec3 = origem.diagsec3,
        diagsec4 = origem.diagsec4,
        diagsec5 = origem.diagsec5,
        diagsec6 = origem.diagsec6,
        diagsec7 = origem.diagsec7,
        diagsec8 = origem.diagsec8,
        diagsec9 = origem.diagsec9,
        tpdisec1 = origem.tpdisec1,
        tpdisec2 = origem.tpdisec2,
        tpdisec3 = origem.tpdisec3,
        tpdisec4 = origem.tpdisec4,
        tpdisec5 = origem.tpdisec5,
        tpdisec6 = origem.tpdisec6,
        tpdisec7 = origem.tpdisec7,
        tpdisec8 = origem.tpdisec8,
        tpdisec9 = origem.tpdisec9,
        uf_res = origem.uf_res,
        uf_mov = origem.uf_mov,
        "_competencia" = origem."_competencia",
        "_source_file" = origem."_source_file",
        "_ingested_at" = origem."_ingested_at",
        "_silver_at" = origem."_silver_at"
WHEN NOT MATCHED THEN INSERT (
        uf_zi,
        ano_cmpt,
        mes_cmpt,
        espec,
        cgc_hosp,
        n_aih,
        ident,
        cep,
        munic_res,
        nasc,
        sexo,
        uti_mes_in,
        uti_mes_an,
        uti_mes_al,
        uti_mes_to,
        marca_uti,
        uti_int_in,
        uti_int_an,
        uti_int_al,
        uti_int_to,
        diar_acom,
        qt_diarias,
        proc_solic,
        proc_rea,
        val_sh,
        val_sp,
        val_sadt,
        val_rn,
        val_acomp,
        val_ortp,
        val_sangue,
        val_sadtsr,
        val_transp,
        val_obsang,
        val_ped1ac,
        val_tot,
        val_uti,
        us_tot,
        dt_inter,
        dt_saida,
        diag_princ,
        diag_secun,
        cobranca,
        natureza,
        nat_jur,
        gestao,
        rubrica,
        ind_vdrl,
        munic_mov,
        cod_idade,
        idade,
        dias_perm,
        morte,
        nacional,
        num_proc,
        car_int,
        tot_pt_sp,
        cpf_aut,
        homonimo,
        num_filhos,
        instru,
        cid_notif,
        contracep1,
        contracep2,
        gestrisco,
        insc_pn,
        seq_aih5,
        cbor,
        cnaer,
        vincprev,
        gestor_cod,
        gestor_tp,
        gestor_cpf,
        gestor_dt,
        cnes,
        cnpj_mant,
        infehosp,
        cid_asso,
        cid_morte,
        complex,
        financ,
        faec_tp,
        regct,
        raca_cor,
        etnia,
        sequencia,
        remessa,
        aud_just,
        sis_just,
        val_sh_fed,
        val_sp_fed,
        val_sh_ges,
        val_sp_ges,
        val_uci,
        marca_uci,
        diagsec1,
        diagsec2,
        diagsec3,
        diagsec4,
        diagsec5,
        diagsec6,
        diagsec7,
        diagsec8,
        diagsec9,
        tpdisec1,
        tpdisec2,
        tpdisec3,
        tpdisec4,
        tpdisec5,
        tpdisec6,
        tpdisec7,
        tpdisec8,
        tpdisec9,
        uf_res,
        uf_mov,
        "_competencia",
        "_source_file",
        "_ingested_at",
        "_silver_at"
) VALUES (
        origem.uf_zi,
        origem.ano_cmpt,
        origem.mes_cmpt,
        origem.espec,
        origem.cgc_hosp,
        origem.n_aih,
        origem.ident,
        origem.cep,
        origem.munic_res,
        origem.nasc,
        origem.sexo,
        origem.uti_mes_in,
        origem.uti_mes_an,
        origem.uti_mes_al,
        origem.uti_mes_to,
        origem.marca_uti,
        origem.uti_int_in,
        origem.uti_int_an,
        origem.uti_int_al,
        origem.uti_int_to,
        origem.diar_acom,
        origem.qt_diarias,
        origem.proc_solic,
        origem.proc_rea,
        origem.val_sh,
        origem.val_sp,
        origem.val_sadt,
        origem.val_rn,
        origem.val_acomp,
        origem.val_ortp,
        origem.val_sangue,
        origem.val_sadtsr,
        origem.val_transp,
        origem.val_obsang,
        origem.val_ped1ac,
        origem.val_tot,
        origem.val_uti,
        origem.us_tot,
        origem.dt_inter,
        origem.dt_saida,
        origem.diag_princ,
        origem.diag_secun,
        origem.cobranca,
        origem.natureza,
        origem.nat_jur,
        origem.gestao,
        origem.rubrica,
        origem.ind_vdrl,
        origem.munic_mov,
        origem.cod_idade,
        origem.idade,
        origem.dias_perm,
        origem.morte,
        origem.nacional,
        origem.num_proc,
        origem.car_int,
        origem.tot_pt_sp,
        origem.cpf_aut,
        origem.homonimo,
        origem.num_filhos,
        origem.instru,
        origem.cid_notif,
        origem.contracep1,
        origem.contracep2,
        origem.gestrisco,
        origem.insc_pn,
        origem.seq_aih5,
        origem.cbor,
        origem.cnaer,
        origem.vincprev,
        origem.gestor_cod,
        origem.gestor_tp,
        origem.gestor_cpf,
        origem.gestor_dt,
        origem.cnes,
        origem.cnpj_mant,
        origem.infehosp,
        origem.cid_asso,
        origem.cid_morte,
        origem.complex,
        origem.financ,
        origem.faec_tp,
        origem.regct,
        origem.raca_cor,
        origem.etnia,
        origem.sequencia,
        origem.remessa,
        origem.aud_just,
        origem.sis_just,
        origem.val_sh_fed,
        origem.val_sp_fed,
        origem.val_sh_ges,
        origem.val_sp_ges,
        origem.val_uci,
        origem.marca_uci,
        origem.diagsec1,
        origem.diagsec2,
        origem.diagsec3,
        origem.diagsec4,
        origem.diagsec5,
        origem.diagsec6,
        origem.diagsec7,
        origem.diagsec8,
        origem.diagsec9,
        origem.tpdisec1,
        origem.tpdisec2,
        origem.tpdisec3,
        origem.tpdisec4,
        origem.tpdisec5,
        origem.tpdisec6,
        origem.tpdisec7,
        origem.tpdisec8,
        origem.tpdisec9,
        origem.uf_res,
        origem.uf_mov,
        origem."_competencia",
        origem."_source_file",
        origem."_ingested_at",
        origem."_silver_at"
)
