-- Silver do SIH/SUS: AIH tipada e deduplicada por numero de AIH.
-- Os 29 campos com zero a esquerda, como proc_rea e cep, continuam varchar,
-- porque o zero neles e informacao e nao formatacao.
-- Particionado pelo mes da internacao e nao pela competencia, porque
-- competencia e mes de faturamento: a fatura de janeiro traz internacoes
-- de meses anteriores, e a analise de ocupacao filtra por data de internacao.

CREATE TABLE IF NOT EXISTS iceberg.silver.sih_aih (
    uf_zi varchar,
    ano_cmpt varchar,
    mes_cmpt varchar,
    espec varchar,
    cgc_hosp varchar,
    n_aih varchar,
    ident varchar,
    cep varchar,
    munic_res varchar,
    nasc date,
    sexo varchar,
    uti_mes_in integer,
    uti_mes_an integer,
    uti_mes_al integer,
    uti_mes_to integer,
    marca_uti varchar,
    uti_int_in integer,
    uti_int_an integer,
    uti_int_al integer,
    uti_int_to integer,
    diar_acom integer,
    qt_diarias integer,
    proc_solic varchar,
    proc_rea varchar,
    val_sh decimal(12,2),
    val_sp decimal(12,2),
    val_sadt decimal(12,2),
    val_rn decimal(12,2),
    val_acomp decimal(12,2),
    val_ortp decimal(12,2),
    val_sangue decimal(12,2),
    val_sadtsr decimal(12,2),
    val_transp decimal(12,2),
    val_obsang decimal(12,2),
    val_ped1ac decimal(12,2),
    val_tot decimal(12,2),
    val_uti decimal(12,2),
    us_tot decimal(12,2),
    dt_inter date,
    dt_saida date,
    diag_princ varchar,
    diag_secun varchar,
    cobranca varchar,
    natureza varchar,
    nat_jur varchar,
    gestao varchar,
    rubrica varchar,
    ind_vdrl varchar,
    munic_mov varchar,
    cod_idade varchar,
    idade integer,
    dias_perm integer,
    morte boolean,
    nacional varchar,
    num_proc varchar,
    car_int varchar,
    tot_pt_sp integer,
    cpf_aut varchar,
    homonimo varchar,
    num_filhos integer,
    instru varchar,
    cid_notif varchar,
    contracep1 varchar,
    contracep2 varchar,
    gestrisco varchar,
    insc_pn varchar,
    seq_aih5 varchar,
    cbor varchar,
    cnaer varchar,
    vincprev varchar,
    gestor_cod varchar,
    gestor_tp varchar,
    gestor_cpf varchar,
    gestor_dt varchar,
    cnes varchar,
    cnpj_mant varchar,
    infehosp varchar,
    cid_asso varchar,
    cid_morte varchar,
    complex varchar,
    financ varchar,
    faec_tp varchar,
    regct varchar,
    raca_cor varchar,
    etnia varchar,
    sequencia integer,
    remessa varchar,
    aud_just varchar,
    sis_just varchar,
    val_sh_fed decimal(12,2),
    val_sp_fed decimal(12,2),
    val_sh_ges decimal(12,2),
    val_sp_ges decimal(12,2),
    val_uci decimal(12,2),
    marca_uci varchar,
    diagsec1 varchar,
    diagsec2 varchar,
    diagsec3 varchar,
    diagsec4 varchar,
    diagsec5 varchar,
    diagsec6 varchar,
    diagsec7 varchar,
    diagsec8 varchar,
    diagsec9 varchar,
    tpdisec1 varchar,
    tpdisec2 varchar,
    tpdisec3 varchar,
    tpdisec4 varchar,
    tpdisec5 varchar,
    tpdisec6 varchar,
    tpdisec7 varchar,
    tpdisec8 varchar,
    tpdisec9 varchar,
    uf_res varchar,
    uf_mov varchar,
    "_competencia" varchar,
    "_source_file" varchar,
    "_ingested_at" timestamp(6) with time zone,
    "_silver_at" timestamp(6) with time zone
)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['month(dt_inter)']
)
