-- Bronze do SIH/SUS: AIH reduzida como veio do DATASUS.
-- Todos os campos de origem sao varchar de proposito. O layout da AIH muda
-- largura e ganha campos entre competencias, e tipar aqui seria transformacao
-- de negocio. A tipagem acontece na silver.
-- Colunas novas em competencias futuras entram por evolucao de schema.

CREATE TABLE IF NOT EXISTS iceberg.bronze.sih_aih (
    uf_zi varchar,
    ano_cmpt varchar,
    mes_cmpt varchar,
    espec varchar,
    cgc_hosp varchar,
    n_aih varchar,
    ident varchar,
    cep varchar,
    munic_res varchar,
    nasc varchar,
    sexo varchar,
    uti_mes_in varchar,
    uti_mes_an varchar,
    uti_mes_al varchar,
    uti_mes_to varchar,
    marca_uti varchar,
    uti_int_in varchar,
    uti_int_an varchar,
    uti_int_al varchar,
    uti_int_to varchar,
    diar_acom varchar,
    qt_diarias varchar,
    proc_solic varchar,
    proc_rea varchar,
    val_sh varchar,
    val_sp varchar,
    val_sadt varchar,
    val_rn varchar,
    val_acomp varchar,
    val_ortp varchar,
    val_sangue varchar,
    val_sadtsr varchar,
    val_transp varchar,
    val_obsang varchar,
    val_ped1ac varchar,
    val_tot varchar,
    val_uti varchar,
    us_tot varchar,
    dt_inter varchar,
    dt_saida varchar,
    diag_princ varchar,
    diag_secun varchar,
    cobranca varchar,
    natureza varchar,
    nat_jur varchar,
    gestao varchar,
    rubrica varchar,
    ind_vdrl varchar,
    munic_mov varchar,
    cod_idade varchar,
    idade varchar,
    dias_perm varchar,
    morte varchar,
    nacional varchar,
    num_proc varchar,
    car_int varchar,
    tot_pt_sp varchar,
    cpf_aut varchar,
    homonimo varchar,
    num_filhos varchar,
    instru varchar,
    cid_notif varchar,
    contracep1 varchar,
    contracep2 varchar,
    gestrisco varchar,
    insc_pn varchar,
    seq_aih5 varchar,
    cbor varchar,
    cnaer varchar,
    vincprev varchar,
    gestor_cod varchar,
    gestor_tp varchar,
    gestor_cpf varchar,
    gestor_dt varchar,
    cnes varchar,
    cnpj_mant varchar,
    infehosp varchar,
    cid_asso varchar,
    cid_morte varchar,
    complex varchar,
    financ varchar,
    faec_tp varchar,
    regct varchar,
    raca_cor varchar,
    etnia varchar,
    sequencia varchar,
    remessa varchar,
    aud_just varchar,
    sis_just varchar,
    val_sh_fed varchar,
    val_sp_fed varchar,
    val_sh_ges varchar,
    val_sp_ges varchar,
    val_uci varchar,
    marca_uci varchar,
    diagsec1 varchar,
    diagsec2 varchar,
    diagsec3 varchar,
    diagsec4 varchar,
    diagsec5 varchar,
    diagsec6 varchar,
    diagsec7 varchar,
    diagsec8 varchar,
    diagsec9 varchar,
    tpdisec1 varchar,
    tpdisec2 varchar,
    tpdisec3 varchar,
    tpdisec4 varchar,
    tpdisec5 varchar,
    tpdisec6 varchar,
    tpdisec7 varchar,
    tpdisec8 varchar,
    tpdisec9 varchar,
    "_ingested_at" timestamp(6) with time zone,
    "_source_file" varchar,
    "_competencia" varchar
)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['"_competencia"']
)
